#!/bin/zsh

# Update cargo dependencies and commit the result.

set -euo pipefail

set -x

cargo upgrade
cargo update

{
  pushd tests/testutils

  cargo upgrade
  cargo update
  cargo upgrade --incompatible
  popd
}

cargo upgrade --incompatible

meta/test

git add Cargo.lock Cargo.toml tests/testutils/Cargo.toml tests/testutils/Cargo.lock
git commit -m 'chore(crates): update cargo dependencies'
