#!/bin/zsh

# Update cargo dependencies and commit the result.

set -euo pipefail

set -x

cargo upgrade

{
  pushd tests/testutils

  cargo upgrade
  cargo upgrade --incompatible
  popd
}

cargo upgrade --incompatible
cargo update

meta/test

git add Cargo.lock Cargo.toml tests/testutils/Cargo.toml
git commit -m 'chore(crates): update cargo dependencies'
