#!/bin/sh

# World's hackiest netrc parser, used solely for testing up-rs.

# Input looks like:
# git credential-netrc get <<<"protocol=https\nhost=github.com\nusername=gib"

# This script assumes your netrc is in the format:
# machine <host>
#   login <user>
#   password <password>

while read line; do
  case "$line" in
    protocol=*) echo "$line" ;;
    host=*)
      host="${line#*=}"
      echo "$line"
      ;;
  esac
done

# Print password=<password>
awk <"$HOME/.netrc" "/^machine $host\$/ { getline; print \"username=\"\$2; getline; print \"password=\"\$2; exit}"
