use anyhow::Result;

use crate::{config, tasks};

pub mod git;

/// Comment to add to top of files generated by this program.
const GENERATED_PRELUDE_COMMENT: &str = "# This file was auto-generated by up-rs.\n";

pub(crate) fn run(config: &config::UpConfig, filter_tasks: &Option<Vec<String>>) -> Result<()> {
    tasks::run(config, filter_tasks, "generate_tasks")
}
